name: Tests
on: [pull_request]
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: |
          flake8 . --count --max-line-length=127 --show-source --statistics

  test:
    needs: lint
    name: Navigator-API pytest
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Prepare venv
        run: |
          pip install pipenv
          ls -la; pwd
          pipenv sync --dev
      - name: Run tests
        run: cd navigator_api; pipenv run pytest


